markdown: kramdown

baseurl: http://www.msapptech.in/clients/ecovar

port: 8000
title:
sass:
  sass_dir: styles
  sourcemap: :true
  style: compact

exclude: ['_site','static-pages','.sass-cache','design']


metadescription:
metakeyword:

img_url: images/site-seo.jpg
encoding: utf-8

# Social media configration
socialMedia:
  - name: Facebook
    link: '#'
    className: facebook-square
  - name: Email
    link: '#'
    className: envelope
  - name: Instagram
    link: '#'
    className: instagram-square

# import external scripts and styles
# if you have maked any property to true it will render on entire page. 
fontawesome: false  # http://fontawesome.io/
slick: false  # http://kenwheeler.github.io/slick/
lazyload: true # http://jquery.eisbehr.de/lazy/
