markdown: kramdown

baseurl: http://www.msapptech.in/clients/ecovar

port: 8000
title:
sass:
  sass_dir: styles
  sourcemap: :true
  style: compact

exclude: ['_site','static-pages','.sass-cache','design']


metadescription:
metakeyword:

img_url: images/site-seo.jpg
encoding: utf-8

# Social media configration
socialMedia:
  - name: Facebook
    link: '#'
    className: facebook-square
  - name: Email
    link: '#'
    className: envelope
  - name: Instagram
    link: '#'
    className: instagram-square
