markdown: Redcarpet
encoding: utf-8
baseurl:
port: 9000 # port for localhost

sass:
  sass_dir: styles
  sourcemap: :true
  style: compact

exclude: ['_site','static-pages','.sass-cache','design','designs']

# SEO
domain: 
metadescription:
metakeyword:
metaImg: images/site-seo.jpg
title:

# Tracking
googleAnalyticsId :  # eg. 'UA-67098409-1' to genrate this code visit on analytics.google.com




# import external scripts and styles
# if you have maked any property to true it will render on entire page.
fontawesome: false  # http://fontawesome.io/
slick: false  # http://kenwheeler.github.io/slick/
lazyload: false # http://jquery.eisbehr.de/lazy/
jssocials: false # http://js-socials.com/
