markdown: Redcarpet

baseurl:

port: 9000 # port for localhost
title:
sass:
  sass_dir: styles
  sourcemap: :true
  style: compact

exclude: ['_site','static-pages','.sass-cache','design']


metadescription: "It seems that you haven't set {{site.metadescription}} or {{page.metadescription}}, It's very great for SEO please add it ASAP"
metakeyword:

mainImg: images/site-seo.jpg
encoding: utf-8



# import external scripts and styles
# if you have maked any property to true it will render on entire page.
fontawesome: true  # http://fontawesome.io/
slick: false  # http://kenwheeler.github.io/slick/
lazyload: false # http://jquery.eisbehr.de/lazy/
jssocials: false # http://js-socials.com/
