markdown: Redcarpet
encoding: utf-8
baseurl:
port: 9000 # port for localhost

sass:
  sass_dir: styles
  sourcemap: :true
  style: compact

exclude: ['_site','static-pages','.sass-cache','design','designs']

# SEO
domain:
metadescription:
metakeyword:
metaImg: images/site-seo.jpg #this must be 1200x650
title:

# Tracking
googleAnalyticsId :  # eg. 'UA-67098409-1' to genrate this code visit on analytics.google.com
